services:
  budgie-agent:
    build:
      context: .
      dockerfile: Dockerfile
    models:
      qwen2_5:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL

models:
  qwen2_5:
    model: ai/qwen2.5:0.5B-F16
