services:

  budgie-workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GO_VERSION=1.24.0
        - TINYGO_VERSION=0.37.0
        - EXTISM_VERSION=1.6.2      # Extism CLI
        - NODE_MAJOR=22
        - USER_NAME=${USER}
    network_mode: "host"  # IMPORTANT: when you work with devcontainer.
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity

